server:
  port: 8999
spring:
  jpa:
    database: mysql
    hibernate: 
      ddl-auto: update  #create-drop
    show-sql: false
    
  datasource: 
      url: jdbc:mysql://122.152.225.103/easycarservice
      username: root
      password: root
  http:
    multipart:
      max-file-size: 10MB
#     location: D:\EasyCarService\tmp
      location: /usr/share/EasyCarService/tmp
  cache:
    ehcache:
      config: classpath:ehcache.xml
  devtools:
    remote:
      debug:
        enabled: true
#  resources:
#    chain:
#      gzipped: true
#      cache: true
#      html-application-cache: true
#      enabled: true
#    cache-period: 120
   
# security debug模式
logging:
#  file: d:\\tmp\\log\\authServer.log
  file: /tmp/log/authServer.log
  level:
    org.springframework.security: info
      
steam:
  api:
    key: 50548F365955D619C1257C3123FB7220
    user-info-url: https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/ 